-- 코드를 작성해주세요
SELECT COUNT(FI.FISH_TYPE) AS FISH_COUNT, FN.FISH_NAME FROM FISH_INFO FI
LEFT JOIN FISH_NAME_INFO FN
ON FI.FISH_TYPE = FN.FISH_TYPE
GROUP BY FI.FISH_TYPE,  FN.FISH_NAME
ORDER BY COUNT(FI.FISH_TYPE) DESC;